spring:
  application:
    name: Backend

  datasource:
    url: jdbc:postgresql://localhost:5432/fyp_db
    username: postgres
    password: ElephantGod123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: FMb1XgNf5fiqwVUxSe2qG55ZVeFzGamyMcMPFRxKJzQ=

server:
  port: 8080