spring:
  application:
    name: Backend

  datasource:
    url: jdbc:postgresql://localhost:5432/fyp_db
    username: postgres
    password: ElephantGod123

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  secret: FMb1XgNf5fiqwVUxSe2qG55ZVeFzGamyMcMPFRxKJzQ=

server:
  port: 8080